name: Release
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  # See https://docs.npmjs.com/trusted-publishers
  id-token: write
  contents: read
  packages: write

jobs:
  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          run_install: false
          version: 11

      - name: Set up Node.js for NPM
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm publish --no-git-checks

  publish-gpr:
    name: Publish on GPR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          run_install: false
          version: 11

      - name: Set up Node.js for GPR
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://npm.pkg.github.com/
          package-manager-cache: false
          scope: '@endbug'

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
